spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/walsupring-tdd}
    username: ${db.username:1234}
    password: ${db.password:1234}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #mysql? ??? ?? ?? ????
        format_sql: true
    show-sql: true
